all:
  vars:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"

  children:

    platformapi:
      vars:
        ansible_user: ec2-user
        ansible_ssh_private_key_file: /home/ec2-user/Capstone-Project/apps/terraform/platformapi_key
      hosts:
        18.144.29.14:
        50.18.130.21:

    zos:
      vars:
        ansible_user: IBMUSER
        ansible_ssh_private_key_file: /home/ec2-user/Capstone-Project/apps/terraform/mainframe_key
        ansible_python_interpreter: /usr/lpp/IBM/cyp/v3r11/pyz/bin/python
      hosts:
        mainframe:
          ansible_host: 67.217.62.83
