all:
  children:
    platformapi:
      hosts:
        54.177.24.138:
          ansible_user: ec2-user
          ansible_ssh_private_key_file: /home/app/.ssh/id_rsa
        50.18.84.244:
          ansible_user: ec2-user
          ansible_ssh_private_key_file: /home/app/.ssh/id_rsa
